### ISSUE TITLE
Adopting Alarm Panel Pro 1.8 breaks ethernet

### ISSUE THREAD

**Issue by d4l3k** [konnected-io/konnected-esphome#15]
Hi, I recently broke ethernet on my device by clicking the adopt button in ESPHome. Documenting the issue so others can fix it as well.

The default config when adopting uses the LAN8720 config rather than the RTL8201 config needed by Alarm Panel Pro 1.8.

```
lan87xx: lan87xx_init(499): wrong chip ID
```

Updating the esphome configuration to use:

```
  konnected.alarm-panel-pro-esp32-wifi: github://konnected-io/konnected-esphome/release/alarm-panel-pro-esp32-rtl8201.yaml@master
```
instead of the generic one on master resolves the issue.

It seems like the dashboard_import section should be changed for the release builds to point to the specific configs rather than the generic one.

https://github.com/konnected-io/konnected-esphome/blob/master/alarm-panel-pro-esp32-ethernet.yaml#L93-L94

**Comment by wjwnz** [comment]
I think I may be having the same issue deploying from the ESPHome integration in Home Assistant:

https://github.com/konnected-io/konnected-esphome/issues/22

Will console into the alarm later and see, mine is also 1.8 Pro

**Comment by heythisisnate** [comment]
Add the following to the top of your adopted YAML in the _substitutions_ section:
```
  ethernet_type: RTL8201
```

For an **Alarm Panel Pro v1.8** connecting via **Ethernet** your adopted YAML config should look like this:

```
substitutions:
  name: alarm-panel-pro-XXXXXX
  ethernet_type: RTL8201 # Alarm Panel Pro 1.8 and up
packages:
  konnected.alarm-panel-pro-esp32-ethernet: github://konnected-io/konnected-esphome/alarm-panel-pro-esp32-ethernet.yaml@master
esphome:
  name: ${name}
  name_add_mac_suffix: false

api:
  encryption:
    key: XXXXXX

# add any customizations here
```
