### ISSUE TITLE
Additional substitution to set allow_other_uses to false for alarm pin

### ISSUE THREAD

**Issue by jcbshw** [konnected-io/konnected-esphome#27]
Would it be possible to add a substitution to set allow_other_uses to false for the alarm pin?

Currently there is only the substitution for the warning beep pin. My alarm pin is only used for the alarm so it currently fails to build.

```
  Pin 15 incorrectly sets allow_other_uses: true.
  platform: gpio
  id: siren
  name: Siren
  pin: 
    number: 15
    allow_other_uses: True
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
      analog: False
    inverted: False
  icon: mdi:bullhorn
  disabled_by_default: False
  restore_mode: ALWAYS_OFF
  interlock_wait_time: 0ms
```
