### ISSUE TITLE
wifi signal using % which is not a valid unit for device class signal_strength

### ISSUE THREAD

**Issue by si458** [konnected-io/konnected-esphome#44]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:737
integration: Sensor (documentation, issues)
First occurred: 11:44:03 (1 occurrences)
Last logged: 11:44:03

Entity sensor.alarm_panel_529364_wifi_signal (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dBm', 'dB']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22

```
substitutions:
  name: alarm-panel-529364
  friendly_name: Alarm Panel 529364

packages:
  konnected.alarm-panel-esp8266: github://konnected-io/konnected-esphome/alarm-panel-esp8266.yaml@master

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: ENCRYPTIONKEYGOESHERE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - id: !extend zone1
    device_class: door
    name: Front Door
  - id: !extend zone2
    device_class: motion
    name: Kitchen
  - id: !extend zone3
    device_class: motion
    name: Living Room
```
