### ISSUE TITLE
ESPHome/Home Assistant - Sensor gets stuck on opening

### ISSUE THREAD

**Issue by omayhemo** [konnected-io/konnected-esphome#59]
Garage door is closed, but the status in home assistant is opening.  I have two, both do the same thing periodically.  Each time the garage door is closed, when the status appears as Opening in Home Assistant.  I've adopted both sensors into ESPHome.

The yaml is as follows:
```
packages:
  konnected.garage-door-esp8266: github://konnected-io/konnected-esphome/garage-door-esp8266.yaml@master
esphome:
  name: garage-door-west
  friendly_name: "Garage Door West"
api:
  encryption:
    key: "REDACTED"

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password
  use_address: REDACTED
  ap:
    ssid: "Garage-Door-West"
    password: "REDACTED"

# Enable logging
logger:

ota:
  password: "REDACTED"


  # Enable fallback hotspot (captive portal) in case wifi connection fails


captive_portal:
   ```
