### ISSUE TITLE
Door close command not working on Merlin GDO wih blaQ

### ISSUE THREAD

**Issue by BenJamesAndo** [konnected-io/konnected-esphome#61]
Hello. I recently received my blaQ. I have a Merlin Commander Elite [MS105MYQ](https://cgi.widen.net/s/rrbdxvzgxs/114a5180h) here in Australia. From reading through https://github.com/ratgdo/esphome-ratgdo/issues/146 it seems others have faced similar issues where the door close command doesn't work. Just wondering what my options are with the blaQ? Does it allow for the toggle command? I tried calling the cover toggle service from HA but it didn't do anything. I can toggle the light, open the door and see numerous statues. I cannot stop it or move it to a particular position, only open it. I had to put the red wire into the green e-serial (0) port and the white wire into the second white (2) port.

I'm running the latest version. Do I need to buy a safety sensor in order to get it to work?

This is my current ESPHome config (the default one that got imported)
```
substitutions:
  name: konnected-612768
  friendly_name: GDO blaQ 612768
packages:
  konnected.garage-door-gdov2-q: github://konnected-io/konnected-esphome/garage-door-GDOv2-Q.yaml@v1-smart-panel-protocol
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
![image](https://github.com/konnected-io/konnected-esphome/assets/44917135/cbf6ea7c-12df-4631-809f-856e0a041eeb)
