### ISSUE TITLE
WiFi Signal % is using the wrong `device_class`

### ISSUE THREAD

**Issue by ptr727** [konnected-io/konnected-esphome#76]
HA reports:

```log
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:709
integration: Sensor (documentation, issues)
First occurred: 6:25:07 PM (1 occurrences)
Last logged: 6:25:07 PM

Entity sensor.konnected_f0f5bd51a9e0_wifi_signal_2 (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dB', 'dBm']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
```

In [code](https://github.com/konnected-io/konnected-esphome/blob/4e073f609fd4a8a10477b8b26ef1833150cea97b/packages/wifi.yaml#L15):

```yaml
  - platform: copy
    source_id: wifi_signal_db
    id: wifi_signal_pct
    name: WiFi Signal %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
```

WiFi signal is copied from source with a device class that requires dB as unit.  
Set an explicit device class to make HA happy.

E.g. in ESPHome [docs](https://esphome.io/components/sensor/wifi_signal.html) the device class of the % is set to "":

```yaml
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
```
