### ISSUE TITLE
Alarm Panel (not Pro) - Out / Alarm GPIO

### ISSUE THREAD

**Issue by liambresnahan** [konnected-io/konnected-esphome#79]
I'm working on an ESPHome implementation of konnected with the interface boards and trying to build something currently that uses the GPIO and a zone (keyswitch) to set alarm state. Using the alarm panel board I'm getting a compiler error stating that the GPIO pin is shared. Looking at alarm-panel-esp8266.yaml it does appear to share D8 with alarm.

Is this correct? How should I be creating a home assistant / esphome configuration to utilize the relay here please?

For context, my YAML includes;

```
switch: 
  - platform: gpio
    id: btnArmDisarmFull
    pin: $out
    name: 'btn-do-ArmDisarm-Full'
    on_turn_on:
     - delay: 400ms
     - switch.turn_off: btnArmDisarmFull
```

Which produces a compiler error stating;

```
INFO ESPHome 2025.3.2
INFO Reading configuration /config/esphome/konnected-9baf4f.yaml...
Failed config

switch.gpio: [source /config/esphome/konnected-9baf4f.yaml:51]
  
  Pin 15 is used in multiple places.
  platform: gpio
  id: btnArmDisarmFull
  pin: 
    number: 15
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
      analog: False
    inverted: False
```
